V1_KEY_MAP = {
    "sender": "s",
    "receiver": "r",
    "intent": "i",
    "context": "c",
    "message": "m",
    "messages": "msgs",
    "status": "st",
    "error_state": "err",
    "content": "ct",
    "role": "rl",
    "name": "n",
    "history": "h",
    "current_task": "ct_",
    "retry_logic": "rtl",
    "unmapped_data": "ud",
    "type": "t",
    "value": "v",
    "data": "dat",
    "text": "tx",
    "query": "q",
    "prompt": "prm",
    "completion": "cmp",
    "model": "mdl",
    "temperature": "tmp",
    "max_tokens": "mxt",
    "stop": "stp",
    "stream": "strm",
    "frequency_penalty": "fp",
    "presence_penalty": "pp",
    "top_p": "tp",
    "n": "n_",
    "choices": "ch_",
    "finish_reason": "fr",
    "usage": "usg",
    "prompt_tokens": "ptk",
    "completion_tokens": "ctk",
    "total_tokens": "ttk",
    "function_call": "fc",
    "tool_calls": "tc",
    "tool_call_id": "tid",
    "tool_name": "tn",
    "tool_input": "ti",
    "tool_output": "tout",
    "arguments": "ar",
    "description": "d",
    "parameters": "p",
    "response": "rsp",
    "result": "res",
    "output": "o",
    "input": "in_",
    "thoughts": "th",
    "action": "a",
    "action_input": "ai",
    "observation": "ob",
    "final_answer": "fa",
    "intermediate_steps": "is_",
    "agent_scratchpad": "as_",
    "system_message": "sm",
    "human_message": "hm",
    "ai_message": "am",
    "chat_history": "ch",
    "memory": "mem",
    "metadata": "md",
    "timestamp": "ts",
    "error": "e",
    "traceback": "tb",
    "exception": "ex",
    "stack_trace": "stk",
    "task": "tsk",
    "tasks": "tsks",
    "subtask": "stsk",
    "plan": "pln",
    "step": "stp_",
    "steps": "stps",
    "iteration": "itr",
    "max_iterations": "mxi",
    "verbose": "vb",
    "callbacks": "cb",
    "tags": "tgs",
    "source": "src",
    "destination": "dst",
    "config": "cfg",
    "settings": "set",
    "options": "opt",
    "flags": "flg",
    "priority": "pri",
    "weight": "wt",
    "score": "sc",
    "confidence": "conf",
    "reasoning": "rsn",
    "explanation": "exp",
    "summary": "sum",
    "title": "ttl",
    "category": "cat",
    "label": "lbl",
    "id": "id",
    "uuid": "uid",
    "session_id": "sid",
    "request_id": "rid",
    "parent_id": "pid",
    "children": "chd",
    "dependencies": "dep",
}

V1_DICTIONARY = {
    "You are a helpful assistant.": "sys:ha",
    "You are a helpful AI assistant.": "sys:ha+",
    "You are an AI assistant that helps people find information.": "sys:info",
    "You are a senior AI agent.": "sys:sr",
    "You are an expert software engineer.": "sys:eng",
    "You are an expert data scientist.": "sys:ds",
    "You are a senior software engineer with expertise in": "sys:eng+",
    "You are a helpful, harmless, and honest assistant.": "sys:hhh",
    "You are an autonomous AI agent.": "sys:auto",
    "You are a ReAct agent. You must reason and act step by step.": "sys:react",
    "You have access to the following tools:": "sys:tools:",
    "Always respond in JSON format.": "sys:json",
    "Always respond in valid JSON.": "sys:json+",
    "Respond only with valid JSON, no explanation.": "sys:json!",
    "Do not include any explanation outside of the JSON.": "sys:nexp",
    "Think step by step before answering.": "sys:CoT",
    "Always Request Clarification if confused.": "mode:?",
    "You must complete the task using the provided tools only.": "sys:tools!",
    "Do not make up information. If you don't know, say so.": "sys:honest",
    "Your goal is to complete the assigned task efficiently.": "sys:goal",
    "You are operating in a multi-agent environment.": "sys:multi",
    "Communicate only using the defined protocol.": "sys:proto",
    "Use chain-of-thought reasoning for all responses.": "sys:CoT+",
    "You will be given a task. Break it into subtasks.": "sys:decomp",
    "You are a planner agent. Create a detailed execution plan.": "sys:plan",
    "You are an executor agent. Execute the given plan step by step.": "sys:exec",
    "You are a critic agent. Evaluate the output for correctness.": "sys:critic",
    "You are a summarizer agent. Summarize the given context.": "sys:sum",
    "Only output the final answer. No intermediate steps.": "sys:final",
    "I encountered the following error:": "E:",
    "Please advise on how to proceed.": "?",
    "I need more information to continue.": "?+",
    "The operation completed successfully.": "OK",
    "An unexpected error occurred during execution.": "E!",
    "I will now attempt to fix the issue.": "fix>",
    "The task has been completed successfully.": "done",
    "I am going to retry the operation.": "retry>",
    "Please provide additional context.": "?ctx",
    "The following steps were executed:": "steps:",
    "I was unable to complete the task.": "FAIL",
    "Based on my analysis, the solution is:": "sol:",
    "I will execute the tool to deploy.": "deploy>",
    "Fix the syntax and try again.": "fix_syn",
    "Running again...": "re>",
    "Please deploy the application.": "dep_app",
    "I have successfully completed the task.": "done+",
    "The task requires additional information.": "?info",
    "I will now proceed with the next step.": "next>",
    "Processing your request...": "proc>",
    "Analyzing the provided data...": "ana>",
    "Generating the response...": "gen>",
    "Executing the plan...": "exec>",
    "Waiting for tool response...": "wait>",
    "Tool execution complete.": "tool_done",
    "Delegating to sub-agent...": "delegate>",
    "Sub-agent response received.": "sub_done",
    "All steps completed. Final answer below.": "final:",
    "I need to use a tool to answer this.": "tool>",
    "Let me search for that information.": "search>",
    "I will now call the function.": "call>",
    "The function returned the following:": "ret:",
    "Here is my step-by-step plan:": "plan:",
    "Step 1:": "S1:",
    "Step 2:": "S2:",
    "Step 3:": "S3:",
    "Step 4:": "S4:",
    "Step 5:": "S5:",
    "Observation:": "Obs:",
    "Thought:": "Tht:",
    "Action:": "Act:",
    "Action Input:": "ActIn:",
    "Final Answer:": "Ans:",
    "Request Clarification": "Prashna",
    "Task Complete": "Purna",
    "Executing Tool": "Karya",
    "Formulating Plan": "Yojana",
    "Waiting for Response": "Pratiksha",
    "Delegating Task": "Niyojana",
    "Reporting Results": "Phala",
    "Analyzing Data": "Vishleshan",
    "Reviewing Output": "Samiksha",
    "Executing Plan": "Kriyavali",
    "Requesting Tool": "Upakarna",
    "Validating Result": "Pariksha",
    "Summarizing Context": "Sangraha",
    "Escalating Issue": "Uttarana",
    "Terminating Session": "Samapti",
    "Initializing Agent": "Arambha",
    "Updating Memory": "Smarana",
    "Broadcasting Message": "Prasara",
    "system": "sys",
    "user": "usr",
    "assistant": "ast",
    "agent": "agt",
    "tool": "tl",
    "function": "fn",
    "human": "hmn",
    "planner": "plnr",
    "executor": "exctr",
    "critic": "crtc",
    "orchestrator": "orch",
    "supervisor": "supv",
    "worker": "wkr",
    "manager": "mgr",
    "failed": "F",
    "success": "S",
    "pending": "P",
    "running": "R",
    "completed": "C",
    "error": "ERR",
    "timeout": "TO",
    "cancelled": "CX",
    "in_progress": "IP",
    "blocked": "BLK",
    "skipped": "SKP",
    "retrying": "RTY",
    "aborted": "ABT",
    "unknown": "UNK",
    "initializing": "INIT",
    "ready": "RDY",
    "idle": "IDL",
    "active": "ACT",
    "NullPointerException: object reference not set": "ShunyaDosha",
    "IndexError: list index out of range": "KramaBhanga",
    "SyntaxError: invalid syntax": "VyakarnaDosha",
    "TimeoutError: operation timed out": "KalaAtikrama",
    "MemoryError: out of memory": "SmritiBhara",
    "FileNotFoundError: no such file or directory": "PathNash",
    "ConnectionError: failed to establish connection": "BandhanDosha",
    "PermissionError: access denied": "AdhikarDosha",
    "KeyError: key not found": "KunjiNash",
    "ValueError: invalid value": "MulyaDosha",
    "TypeError: unsupported operand type": "PrakarDosha",
    "RecursionError: maximum recursion depth exceeded": "PunarAvritiDosha",
    "ZeroDivisionError: division by zero": "ShunayaBhaga",
    "AttributeError: object has no attribute": "GunaDosha",
    "ImportError: no module named": "AayaatDosha",
    "RuntimeError: CUDA out of memory": "GpuSmritiBhara",
    "JSONDecodeError: Expecting value": "JsonDosha",
    "AssertionError": "DridhaDosha",
    "StopIteration": "KramaAnta",
    "OverflowError: integer overflow": "AtikramaDosha",
    "UnicodeDecodeError": "VarnaDosha",
    "OSError: no space left on device": "SthanNash",
    "HTTPError: 429 Too Many Requests": "SeemaDosha",
    "HTTPError: 401 Unauthorized": "PraveshDosha",
    "HTTPError: 403 Forbidden": "NishedhDosha",
    "HTTPError: 404 Not Found": "AnupastitiDosha",
    "HTTPError: 500 Internal Server Error": "ServerDosha",
    "Let me think about this step by step.": "CoT>",
    "I will break this down into smaller steps.": "decomp>",
    "Here is my analysis of the situation:": "ana:",
    "I have identified the root cause:": "root:",
    "The deployment failed.": "dep_F",
    "The deployment succeeded.": "dep_S",
    "I need to call a tool.": "tool_call>",
    "I will now summarize the results.": "sum>",
    "The context window is getting full.": "ctx_full",
    "I am passing this to the next agent.": "pass>",
    "Received task from orchestrator.": "recv_tsk",
    "Sending result to orchestrator.": "send_res",
    "No further action required.": "NOP",
    "I cannot complete this task.": "FAIL+",
    "This task is outside my capabilities.": "OOB",
    "Escalating to supervisor agent.": "esc>",
    "The previous step failed. Retrying.": "prev_F>retry",
    "All subtasks complete.": "subtsk_done",
    "Beginning task execution.": "begin>",
    "Task execution complete.": "exec_done",
    "Verifying output integrity.": "verify>",
    "Output verified successfully.": "verify_S",
    "Output verification failed.": "verify_F",
    "Storing result in memory.": "mem>",
    "Retrieved from memory:": "mem_ret:",
    "Memory updated successfully.": "mem_S",
    "Initializing tool call.": "tc_init>",
    "Tool call successful.": "tc_S",
    "Tool call failed.": "tc_F",
    "Retrying tool call.": "tc_retry>",
    "Agent A": "AgA",
    "Agent B": "AgB",
    "Agent C": "AgC",
    "Agent D": "AgD",
    "DeployScript": "DS",
    "PlannerAgent": "PA",
    "ExecutorAgent": "EA",
    "CriticAgent": "CA",
    "OrchestratorAgent": "OA",
    "ResearchAgent": "RA",
    "SummaryAgent": "SA",
    "ValidatorAgent": "VA",
}

EXTENDED_KEY_MAP = {
    "agent_id": "aid",
    "agent_name": "an",
    "agent_role": "ar_",
    "agent_type": "at",
    "assistant_message": "amsg",
    "attributes": "attrs",
    "auth": "au",
    "authentication": "auth",
    "author": "aut",
    "available_tools": "at_",
    "base_url": "bu",
    "batch": "btch",
    "body": "bd",
    "branch": "br",
    "buffer": "buf",
    "build": "bld",
    "cache": "cch",
    "callback_url": "cbu",
    "channel": "chn",
    "chat": "cht",
    "chunk": "chk",
    "code": "cd",
    "color": "clr",
    "command": "cmd",
    "comment": "cmt",
    "completed_at": "cat",
    "component": "cmp_",
    "condition": "cnd",
    "connection": "conn",
    "container": "cntr",
    "content_type": "ctp",
    "context_window": "cwn",
    "conversation": "conv",
    "count": "cnt",
    "country": "cntry",
    "created_at": "cra",
    "credential": "cred",
    "currency": "cur",
    "current": "cur_",
    "custom": "cstm",
    "dataset": "ds",
    "deadline": "ddl",
    "default": "dflt",
    "deleted": "del",
    "delivered": "dlv",
    "depth": "dpt",
    "destination_url": "durl",
    "details": "dtl",
    "device": "dev",
    "dimension": "dim",
    "directory": "dir",
    "document": "doc",
    "domain": "dmn",
    "duration": "dur",
    "email": "em",
    "embedding": "emb",
    "enabled": "enb",
    "encoding": "enc",
    "endpoint": "ept",
    "engine": "eng",
    "environment": "env",
    "event": "evt",
    "event_id": "eid",
    "execute": "exec_",
    "expected": "exp_",
    "expires": "exp",
    "failure": "flr",
    "feature": "ftr",
    "feedback": "fdb",
    "field": "fld",
    "filename": "fnm",
    "filter": "flt",
    "first_name": "fn",
    "format": "fmt",
    "frequency": "freq",
    "function_name": "fnm_",
    "gradient": "grad",
    "group": "grp",
    "handler": "hdl",
    "headers": "hdr",
    "height": "hgt",
    "host": "hst",
    "href": "hrf",
    "icon": "icn",
    "image": "img",
    "index": "idx",
    "initialized": "init_",
    "input_text": "itx",
    "installed": "inst",
    "instruction": "instr",
    "ip_address": "ip",
    "is_active": "ia",
    "is_complete": "ic",
    "is_deleted": "id_",
    "is_enabled": "ie",
    "is_valid": "iv",
    "iteration_count": "itc",
    "job": "jb",
    "key": "ky",
    "keyword": "kwd",
    "language": "lang",
    "last_modified": "lm",
    "last_name": "ln",
    "layer": "lyr",
    "level": "lvl",
    "limit": "lmt",
    "link": "lnk",
    "list": "lst",
    "locale": "lc",
    "location": "loc",
    "log": "lg",
    "machine": "mch",
    "max_length": "mxl",
    "max_retries": "mxr",
    "message_id": "mid",
    "method": "mth",
    "min_length": "mnl",
    "mode": "md",
    "model_name": "mdln",
    "module": "mod",
    "name_space": "ns",
    "namespace": "nsp",
    "network": "net",
    "node": "nde",
    "note": "nte",
    "notes": "ntes",
    "number": "num",
    "object": "obj",
    "offset": "off",
    "operator": "opr",
    "option": "opt_",
    "order": "ord",
    "organization": "org",
    "output_text": "otx",
    "owner": "own",
    "page": "pg",
    "param": "prm_",
    "parent": "par",
    "password": "pwd",
    "path": "pth",
    "pattern": "ptn",
    "payload": "pld",
    "permission": "perm",
    "phase": "phs",
    "platform": "plt",
    "policy": "pol",
    "port": "prt",
    "previous": "prv",
    "price": "prc",
    "probability": "prob",
    "process": "proc",
    "processor": "proc_",
    "program": "pgm",
    "project": "prj",
    "protocol": "proto",
    "provider": "prov",
    "proxy": "prx",
    "queue": "que",
    "rate": "rte",
    "ratio": "rto",
    "reason": "rsn_",
    "record": "rec_",
    "reference": "ref",
    "region": "rgn",
    "registry": "reg",
    "rejected": "rj",
    "released": "rel",
    "remaining": "rem",
    "remote": "rmt",
    "render": "rndr",
    "repeat": "rpt",
    "replace": "rpl",
    "reply": "rpy",
    "repository": "repo",
    "request": "req",
    "required": "req_",
    "resource": "rsrc",
    "response_id": "rid_",
    "restart": "rstrt",
    "revision": "rev",
    "role_id": "rlid",
    "route": "rt",
    "row": "rw",
    "rule": "rul",
    "runtime": "rtm",
    "scale": "scl",
    "schedule": "sched",
    "schema": "schm",
    "scope": "scp",
    "script": "scr",
    "secret": "sec",
    "section": "sct",
    "segment": "seg",
    "selector": "sel",
    "sequence": "seq",
    "server": "srv",
    "service": "svc",
    "session": "ses",
    "shader": "shd",
    "shape": "shp",
    "signature": "sig",
    "size": "sz",
    "slot": "slt",
    "socket": "sck",
    "source_url": "surl",
    "spec": "spc",
    "specification": "spec_",
    "stack": "stkk",
    "stage": "stg",
    "started_at": "sta",
    "state": "ste",
    "stat": "stat",
    "statement": "stmt",
    "status_code": "scd",
    "stop_sequence": "ssq",
    "strategy": "strat",
    "string": "strg",
    "subnet": "snet",
    "subnet_mask": "smk",
    "subscriber": "sub",
    "subscription": "sub_",
    "success_rate": "sr",
    "symbol": "sym",
    "syntax": "syn",
    "system_prompt": "sp",
    "table": "tbl",
    "target": "tgt",
    "tenant": "tnt",
    "tenant_id": "tid_",
    "term": "trm",
    "thread": "thrd",
    "thread_id": "thid",
    "thumbnail": "thumb",
    "timeout_ms": "tms",
    "timezone": "tz",
    "token": "tkn",
    "token_count": "tct",
    "topic": "tpc",
    "total": "tot",
    "trace": "trc",
    "trigger": "trg",
    "type_name": "tnm",
    "unique": "unq",
    "updated_at": "upa",
    "uploaded": "uld",
    "url": "url",
    "user_id": "uid_",
    "user_name": "un",
    "username": "usrn",
    "validator": "vld",
    "vector": "vct",
    "version": "ver",
    "video": "vid",
    "volume": "vol",
    "warning": "wrn",
    "webhook": "whk",
    "weight_id": "wid",
    "width": "wdt",
    "workflow": "wkf",
    "workspace": "wks",
}

SAMASA_DICTIONARY = {
    "the request was successful": "Sadhya",
    "request clarification": "PrashnaSanketa",
    "task execution": "KaryaPravritti",
    "system prompt": "PranaliVakya",
    "tool response": "UpakaranaUttara",
    "error handling": "DoshaSamhara",
    "memory update": "SmritiParivardhana",
    "context window": "SanketaKshetra",
    "deployment failure": "NiyojanaDosha",
    "response generation": "UttaraJanana",
    "session management": "SatraSthapana",
    "please review the following information": "VishayKrama",
    "the system is currently processing": "PranaliKriya",
    "no further action is required at this time": "NaKarya",
    "the data has been successfully validated": "TattvaPari",
    "an error has occurred while processing": "PrasadhanaDosha",
    "please confirm the operation was intended": "Sanketa",
    "the operation is queued for execution": "KaryaPankti",
    "the response was generated successfully": "UttaraSadhya",
    "the model is currently loading": "MudraAvarodha",
    "please wait while the system initializes": "Vilamba",
    "the connection has been established": "BandhanSadhya",
    "the session has been terminated": "Sadasamapti",
    "authentication is required to proceed": "PraveshaAvashyak",
    "the resource was not found": "VastuNash",
    "the limit has been exceeded": "SeemaLanghana",
    "the configuration has been updated": "ViniyogaSadhya",
    "the process completed without errors": "DoshRahit",
    "the output is ready for review": "PhalaTatpara",
    "the agent is awaiting instructions": "DutaPratiksha",
}

KARAKA_SUFFIXES = {
    "by": "₁",
    "for": "₂",
    "with": "₃",
    "from": "₄",
    "according to": "₅",
    "because of": "₆",
    "in order to": "₇",
    "instead of": "₈",
    "due to": "₉",
    "via": "₀",
}

KARAKA_INVERSE = {v: k for k, v in KARAKA_SUFFIXES.items()}

ENGLISH_STOPWORD_MAP = {
    "the": "Ω", "a": "Φ", "an": "Ψ",
    "is": "Δ", "are": "Λ", "was": "ω", "were": "ψ", "been": "φ", "being": "χ",
    "of": "ξ", "at": "ζ", "on": "κ", "as": "η",
    "it": "ν", "its": "μ",
    "that": "б", "this": "в", "these": "г", "those": "д",
}

ENGLISH_STOPWORD_INVERSE = {v: k for k, v in ENGLISH_STOPWORD_MAP.items()}

MULTILINGUAL_PHRASE_MAPS = {
    "es": {
        "por favor": "please",
        "revise": "review",
        "la solicitud": "the request",
        "por favor revise la solicitud": "please review the request",
    },
    "fr": {
        "s'il vous plaît": "please",
        "vérifier": "review",
        "la demande": "the request",
    },
    "hi": {
        "कृपया": "please",
        "जाँच": "review",
        "अनुरोध": "request",
    },
}

ENGLISH_AGGLOUTINATION_PHRASES = {
    "access control management": "accessControlManagement",
    "access control management configuration": "accessControlManagementConfiguration",
    "user authentication": "userAuthentication",
    "user authentication timestamp": "userAuthenticationTimestamp",
    "database connection pool": "databaseConnectionPool",
    "error handling logic": "errorHandlingLogic",
    "configuration management": "configurationManagement",
    "state machine diagram": "stateMachineDiagram",
    "version control system": "versionControlSystem",
    "content delivery network": "contentDeliveryNetwork",
    "application programming interface": "applicationProgrammingInterface",
    "machine learning model": "machineLearningModel",
    "natural language processing": "naturalLanguageProcessing",
    "graphical user interface": "graphicalUserInterface",
    "input validation logic": "inputValidationLogic",
    "session management system": "sessionManagementSystem",
    "request response cycle": "requestResponseCycle",
    "dependency injection container": "dependencyInjectionContainer",
    "object relational mapper": "objectRelationalMapper",
    "continuous integration pipeline": "continuousIntegrationPipeline",
    "role based access control": "roleBasedAccessControl",
    "single sign on": "singleSignOn",
    "cross site scripting": "crossSiteScripting",
    "cross site request forgery": "crossSiteRequestForgery",
    "representational state transfer": "representationalStateTransfer",
    "remote procedure call": "remoteProcedureCall",
    "extract transform load": "extractTransformLoad",
    "virtual private network": "virtualPrivateNetwork",
    "infrastructure as code": "infrastructureAsCode",
    "platform as a service": "platformAsAService",
    "software as a service": "softwareAsAService",
    "software development kit": "softwareDevelopmentKit",
    "integrated development environment": "integratedDevelopmentEnvironment",
    "object oriented programming": "objectOrientedProgramming",
    "test driven development": "testDrivenDevelopment",
    "domain driven design": "domainDrivenDesign",
}

SENTINEL_PREFIX = "⟦"
SENTINEL_SUFFIX = "⟧"
REGISTRY_KEY = "⟦reg⟧"
ENVELOPE_KEY = "⟦env⟧"

CODE_FENCE_PATTERN = "```"
INLINE_CODE_PATTERN = "`"
RAW_STRING_PREFIXES = ("r'", 'r"', "r'''", 'r"""', "rb'", 'rb"', "R'", 'R"')

BPE_SAFE_GLYPH_POOL = [
    "₁", "₂", "₃", "₄", "₅", "₆", "₇", "₈", "₉", "₀",
    "Ω", "Ψ", "Φ", "Χ", "Θ", "Ξ", "Σ", "Π", "Δ", "Λ",
    "ω", "ψ", "φ", "χ", "ξ", "ζ", "κ", "η", "ν", "μ",
    "б", "в", "г", "д", "ж", "з", "к", "л", "м", "н",
    "п", "р", "с", "т", "ф", "ц", "ч", "ш", "щ", "ъ",
    "※", "⁂", "⌘", "⌥", "⎈", "◈", "◉", "◊", "☉", "☊",
    "♲", "♳", "♴", "♵", "♶", "♷", "ؘ", "♹", "♺", "♻",
    "⟠", "⟡", "⟢", "⟣", "⟤", "⟥", "⟨", "⟩", "⌬", "⌗",
    "▢", "▣", "▤", "▥", "▦", "▧", "▨", "▩", "◼", "◽",
    "✠", "✡", "✢", "✣", "✤", "✥", "✦", "✧", "✩", "✪",
    "∀", "∁", "∂", "∃", "∄", "∅", "∆", "∇", "∉", "∋",
    "←", "↑", "→", "↓", "↔", "↕", "↖", "↗", "↘", "↙",
    "₨", "₩", "₪", "₫", "₭", "₮", "₯", "₰", "₱", "₲",
    "⁰", "¹", "²", "³", "⁴", "⁵", "⁶", "⁷", "⁸", "⁹",
    "ⅰ", "ⅱ", "ⅲ", "ⅳ", "ⅴ", "ⅵ", "ⅶ", "ⅷ", "ⅸ", "ⅹ",
    "⚀", "⚁", "⚂", "⚃", "⚄", "⚅", "⚆", "⚇", "⚈", "⛁",
    "♈", "♉", "♊", "♋", "♌", "♍", "♎", "♏", "♐", "♑",
]

HUFFMAN_FIXED_TABLE = {
    '|AgA|': "♒A",
    '|AgB|': "♒B",
    '|AgC|': "♒C",
    '|AgD|': "♒D",
    '|Prashna|': "♓Q",
    '|Purna|': "♓P",
    '|Karya|': "♓K",
    '|Yojana|': "♓Y",
    '|Pratiksha|': "♓W",
    '|Niyojana|': "♓N",
    '|Phala|': "♓R",
    '|Vishleshan|': "♓V",
    '|Samiksha|': "♓M",
    '|Kriyavali|': "♓L",
    '|E:|': "♈E",
    '|?|': "♈?",
    '|?+|': "♈+",
    '|OK|': "♈O",
    '|E!|': "♈!",
    '|done|': "♉D",
    '|FAIL|': "♉F",
    '|sys|': "♊S",
    '|usr|': "♊U",
    '|ast|': "♊A",
    '|agt|': "♊G",
    '|tl|': "♊T",
    '|fn|': "♊F",
    '|hmn|': "♊H",
    '|F|': "♋F",
    '|S|': "♋S",
    '|P|': "♋P",
    '|R|': "♋R",
    '|C|': "♋C",
    '|ERR|': "♋E",
    '|TO|': "♋T",
    '":{"': "♌J",
    '":"': "♌Q",
    '","': "♌C",
    ':{': "♌O",
    '},': "♌B",
    '}}': "♌E",
    '][': "♌K",
    ']=': "♌V",
    '"}': "♌X",
}

HUFFMAN_FIXED_INVERSE = {v: k for k, v in HUFFMAN_FIXED_TABLE.items()}

LEVEL_V1 = "v1"
LEVEL_ENTROPY = "entropy"
LEVEL_STRUCTURAL = "structural"
LEVEL_PANINIAN = "paninian"
LEVEL_HYPER = "hyper"

LEVEL_ORDER = [LEVEL_V1, LEVEL_ENTROPY, "structural", LEVEL_PANINIAN, LEVEL_HYPER]

GPT4O_PRICE_PER_MILLION = 5.0
CHARS_PER_TOKEN_ESTIMATE = 4

# Remove any entries from the BPE-safe glyph pool that overlap with
# glyphs used by the fixed Huffman table values. This prevents ambiguity
# between dynamic single-char glyphs and reserved fixed-table glyphs.
try:
    _reserved_huffman_chars = set(''.join(HUFFMAN_FIXED_TABLE.values()))
    BPE_SAFE_GLYPH_POOL = [g for g in BPE_SAFE_GLYPH_POOL if not any(ch in _reserved_huffman_chars for ch in g)]
except Exception:
    # defensive: if something isn't defined yet, skip pruning
    pass
